name: Lesson 5 SAST

on:
  push:
    branches:
      - lesson-5
jobs:
  security_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: Execute the PyCharm security test
    steps:
      - uses: actions/checkout@v4
      - name: Run PyCharm security
        uses: toneybaloney/pycharm-security@1.25.1
  build_and_test:
    needs: [security_test]
    runs on: ubuntu-latest